### ISSUE TITLE
Ошибка в описании механизма PFC

### ISSUE THREAD

**Issue by k01ek** [eucariot/where-to-store-the-packet#3]
Привет! Огромное спасибо за книгу и за остальное творчество. 
Кажется тут закралась ошибка: https://github.com/eucariot/where-to-store-the-packet/blob/master/docs/source/5_buffers/3_buffer_architecture.rst#headroom-buffers
в описании механизма PFC говорится: "Коммутатор, заметив заполнение общего буфера, отправляет Pause для более низкого приоритета, тем самым притормаживая репликацию, но не RoCE." 
На самом деле, при перегрузке, Pause отправляется для no-drop трафика помеченным определенным CoS, каким и  является RoCE. 
Цитата из документа на который есть ссылка в статье:
"When you configure a CNP on an interface, ingress traffic that is mapped to a priority that the CNP enables for PFC is paused whenever the queue buffer fills to the pause threshold. (The pause threshold is not user-configurable.)

Configure PFC for a priority end to end along the entire data path to create a lossless lane of traffic on the network. "

**Comment by eucariot** [comment]
Привет. Спасибо за комментарий.
Действительно я был фундаментально не прав. Исправил.
